#!/bin/bash

# Check if file exists
if [ ! -f "$1" ]; then
  echo "Error: file does not exist."
  exit 1
fi

# Read each line in the file and process it
while read line; do
  url="https://www.google.com/maps/place/$line"
  result=$(wget -qO- "$url" | sed -n 's/.*\/@\([-0-9]*\.[0-9]\{3\}\)\([0-9]*\),\([-0-9]*\.[0-9]\{3\}\)\([0-9]*\).*/\1|\3/p')
  if [ ! -z "$result" ]; then
    echo "$line|$result"
  fi
    sleep $((3 + $RANDOM % 3))
done < "$1"
